name: Codegen Tests
on: [push, pull_request]
env:
  GOPROXY: https://proxy.golang.org
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20' ]
    env:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    name: Go ${{ matrix.go }} generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Coretto 17 JDK
        run: |
          download_url="https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up Coretto 17 JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: 17
          architecture: x64

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set smity-go version
        id: smithy_go_version
        run: echo "version=$(grep smithy-go go.mod | cut -d " " -f 2)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v2
        with:
          repository: aws/smithy-go
          path: tmp-smithy-go
          ref: ${{ steps.smithy_go_version.outputs.version }}

      - name: Build and publish smithy-go
        working-directory: tmp-smithy-go
        run: make smithy-publish-local

      - name: Cleanup smithy-go
        run: rm -rf tmp-smithy-go

      - name: SDK Codegen
        run: make smithy-generate
